# Generated by Django 5.1.3 on 2025-02-02 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_coupon_carbooking_final_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbooking',
            name='product_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='store.car'),
        ),
    ]
