# Generated by Django 5.1.3 on 2025-01-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_carbooking_bookingitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='with_driver',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=50, null=True),
        ),
    ]
