# Generated by Django 5.1.3 on 2025-01-07 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_carbooking_with_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingitem',
            name='total',
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='price_per_day',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='carbooking',
            name='product_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.car'),
        ),
    ]
