# Generated by Django 5.1.3 on 2025-02-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_carbooking_product_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbooking',
            name='total_payment',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
