# Generated by Django 5.1.3 on 2025-02-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_carbooking_total_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbooking',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='carbooking',
            name='total_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
