# Generated by Django 5.1.3 on 2025-01-07 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_bookingitem_total_bookingitem_price_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='is_order_placed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='carbooking',
            name='product_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='store.car'),
        ),
    ]
