# Generated by Django 5.1.3 on 2025-02-03 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_carbooking_final_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='disc_price',
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('flat amount', 'flat Amount')], max_length=20)),
                ('value', models.FloatField()),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='store.car')),
            ],
        ),
    ]
