# Generated by Django 5.1.3 on 2025-01-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_bookingitem_order_object_alter_carbooking_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbooking',
            name='is_order_placed',
            field=models.BooleanField(default=False),
        ),
    ]
