# Generated by Django 5.1.3 on 2025-02-04 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_car_disc_price_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbooking',
            name='coupon_obj',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
