# Generated by Django 5.1.3 on 2025-02-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_carbooking_coupon_obj_delete_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='discount_amount',
            field=models.FloatField(default=0, null=True),
        ),
    ]
