# Generated by Django 5.1.3 on 2025-01-07 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_carbooking_is_order_placed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingitem',
            name='order_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.car'),
        ),
    ]
