# Generated by Django 5.1.3 on 2025-01-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_bookingitem_order_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbooking',
            name='product_object',
        ),
    ]
