# Generated by Django 5.1.3 on 2025-01-07 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_carbooking_product_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='product_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='store.car'),
        ),
    ]
