# Generated by Django 5.1.3 on 2025-01-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_carbooking_product_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingitem',
            name='price_per_day',
            field=models.PositiveIntegerField(),
        ),
    ]
