# Generated by Django 5.1.3 on 2025-02-04 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_carreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarReview',
        ),
    ]
