# Generated by Django 5.1.3 on 2025-01-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_bookingitem_price_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='total_payment',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
